#
#  Java Information Dynamics Toolkit (JIDT)
#  Copyright (C) 2026, Alexander Richter
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""The Java Information Dynamics Toolkit (JIDT), as a Python module.

Every calculator in infodynamics.jar is made available here under its own
name, so that the toolkit may be used from Python without installing a Java
development kit, setting JAVA_HOME, or naming a jar on a class path. The jar
and a Java runtime are supplied with this module.

Usage of the module is intended to follow this paradigm:
    1. Import the module: import jidt;
    2. Construct a calculator, e.g.:
       calc = jidt.MutualInformationCalculatorDiscrete(2);
    3. Initialise the calculator using calc.initialise();
    4. Provide the observations/samples for the calculator to set up the
       PDFs, as lists or numpy arrays, e.g. calc.addObservations(x, y),
       then
    5. Compute the required quantities, e.g. the average MI:
       calc.computeAverageLocalOfObservations();
    6. Return to step 3 to re-use the calculator on a new data set.

Names are unchanged from the Java toolkit, so code written against JIDT
elsewhere (including code generated by the AutoAnalyser) may be pasted here
with only the class lookup removed. The AutoAnalyser itself is launched with
jidt.gui().

Copyright (C) 2026-, Alexander Richter
Distributed under GNU General Public License v3
"""

from __future__ import annotations

import functools
import os
import struct
import subprocess
import zipfile
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _installed_version
from pathlib import Path

import jpype
import numpy as np

# The version of the toolkit we ship, as recorded when this was installed;
# build.xml holds it, and nothing here repeats it:
try:
    __version__ = _installed_version("jidt")
except PackageNotFoundError:  # running from a source tree, not installed
    __version__ = "unknown"
__all__ = ["start", "jclass", "java_home", "check_platform", "gui"]

# The toolkit itself, which is put on the JVM's class path below:
JAR = Path(__file__).with_name("infodynamics.jar")


def java_home() -> Path:
    """Returns the Java runtime that this module will run the toolkit on.

    The runtime supplied by the jdk4py package is used, unless the user
    names another one in JIDT_JAVA_HOME (or JAVA_HOME); e.g. set that if
    you wish to run on a Java installation of your own.

    Outputs:
    - result - path to a Java runtime, in the form JAVA_HOME takes
    """
    override = os.environ.get("JIDT_JAVA_HOME") or os.environ.get("JAVA_HOME")
    if override:
        return Path(override)
    try:
        import jdk4py
    except ImportError:
        # No jdk4py wheel is published for this platform, so there is no
        # runtime to fall back on -- ask the user for one:
        raise RuntimeError(
            "No bundled Java runtime for this platform: install a "
            "JDK and point JIDT_JAVA_HOME (or JAVA_HOME) at it."
        ) from None

    return Path(jdk4py.JAVA_HOME)


def check_platform() -> None:
    """Checks that this Python can host a JVM, throwing an error if not.

    A 32 bit Python cannot load the 64 bit JVM supplied with this module.
    This is checked up front so that the user is told what is wrong, rather
    than meeting an error from inside the JVM.

    Throws a RuntimeError when this Python is not 64 bit
    """
    bits = struct.calcsize("P") * 8
    if bits != 64:
        raise RuntimeError(
            f"jidt needs a 64-bit Python; this one is {bits}-bit. "
            "Install a 64-bit Python and reinstall jidt."
        )


def start(*jvm_args: str) -> None:
    """Starts the JVM with infodynamics.jar on its class path.

    This is called for the user on first use of a calculator, so it need
    only be called directly in order to supply JVM options; and it must
    then be called before any calculator is constructed. The JVM is started
    once per process: later calls do nothing.

    Inputs:
    - jvm_args - options for the JVM, e.g. "-Xmx1024M" to allow it more
      memory if you get crashes on large data sets
    """
    check_platform()
    if jpype.isJVMStarted():
        return
    # JPype finds the runtime through JAVA_HOME, so ours is put there for
    # the one call and the user's environment is then left as it was:
    previous = os.environ.get("JAVA_HOME")
    os.environ["JAVA_HOME"] = str(java_home())
    try:
        jpype.startJVM(
            # Suppresses a warning on Java 22 and later; earlier runtimes
            # do not know this option, hence ignoreUnrecognized below:
            "--enable-native-access=ALL-UNNAMED",
            *jvm_args,
            classpath=[str(JAR)],
            ignoreUnrecognized=True,
        )
    finally:
        if previous is None:
            del os.environ["JAVA_HOME"]
        else:
            os.environ["JAVA_HOME"] = previous


def gui(*jvm_args: str) -> subprocess.Popen:
    """Launches the AutoAnalyser GUI application in a JVM of its own.

    Returns as soon as the application is started, and the windows are not
    tied to this interpreter: they stay up if it exits, and closing them
    does not disturb it. Running the GUI separately is also why it does not
    matter that the toolkit's frames end their process when closed.

    Inputs:
    - jvm_args - options for the GUI's JVM, e.g. "-Xmx1024M"

    Outputs:
    - result - the running process, should you wish to wait for the GUI to
      be closed or to stop it from here
    """
    java = java_home() / "bin" / "java"
    return subprocess.Popen([str(java), *jvm_args, "-jar", str(JAR)])


@functools.cache
def _classes() -> dict[str, str]:
    """Maps each class in the jar from its plain name to its full Java name.

    The jar is read directly, so this costs nothing until a class is asked
    for, does not require the JVM to be running, and is done once. Where a
    plain name occurs in more than one package the shallowest wins, which
    keeps e.g. infodynamics.utils.RandomGenerator ahead of the copy in the
    bundled commons-math.

    Outputs:
    - result - plain class name -> full Java name, e.g.
      "MatrixUtils" -> "infodynamics.utils.MatrixUtils"
    """
    with zipfile.ZipFile(JAR) as z:
        names = [
            n[:-len(".class")].replace("/", ".")
            for n in z.namelist()
            if n.endswith(".class")
            # Inner classes ($) and package documentation are not
            # calculators, so they are left out:
            and "$" not in n
            and not n.endswith("package-info.class")
        ]
    index: dict[str, str] = {}
    for full in sorted(names, key=lambda n: (n.count("."), n)):
        index.setdefault(full.rsplit(".", 1)[1], full)
    return index


def jclass(name: str):
    """Returns a class from the toolkit, starting the JVM if required.

    Inputs:
    - name - plain class name, e.g. "MatrixUtils", or a full Java name,
      e.g. "infodynamics.utils.MatrixUtils"

    Outputs:
    - result - the class, ready to be constructed or called
    """
    start()
    return _Wrapper(jpype.JClass(_classes().get(name, name)))


def __getattr__(name: str):
    # Makes every class in the jar an attribute of this module, so that
    # jidt.MutualInformationCalculatorDiscrete finds the Java class:
    if name.startswith("_") or name not in _classes():
        raise AttributeError(f"module 'jidt' has no attribute {name!r}")
    return jclass(name)


def __dir__() -> list[str]:
    return sorted([*__all__, *_classes()])


def _to_java(value):
    """Converts observations from Python into the Java arrays JIDT takes.

    JPype already matches a list or a 1D numpy array to a Java array, but
    not a 2D one -- which is how multivariate observations are supplied, one
    row per time step -- so those are converted here. Values which are not
    array-like are passed through untouched, as are Java arrays the user
    has built themselves.

    Inputs:
    - value - an argument on its way to a Java method

    Outputs:
    - result - a Java array where one was called for, else value unchanged
    """
    if isinstance(value, np.ndarray):
        array = value
    elif isinstance(value, (list, tuple)):
        try:
            array = np.asarray(value)
        except ValueError:
            # Ragged sequences are not arrays; let Java report on them:
            return value
    else:
        return value
    if array.ndim < 2 or array.dtype.kind not in "biuf":
        return value
    # Continuous observations are double[][] to the toolkit, whilst the
    # discrete calculators operate only on integers, i.e. int[][]:
    if array.dtype.kind == "f":
        jtype, dtype = jpype.JDouble, np.float64
    else:
        jtype, dtype = jpype.JInt, np.int32
    contiguous = np.ascontiguousarray(array, dtype)
    return jpype.JArray(jtype, array.ndim)(contiguous)


def _from_java(value):
    """Converts a result from Java into the Python form expected here.

    Inputs:
    - value - a value returned by a Java method or field

    Outputs:
    - result - a numpy array for a Java array, e.g. for the local values of
      a measure; a wrapped object for a calculator, so that conversion
      continues to apply to it; else value unchanged
    """
    if isinstance(value, jpype.JArray):
        return np.asarray(value)
    if isinstance(value, jpype.JObject) and "infodynamics" in str(type(value)):
        return _Wrapper(value)
    return value


def _call(method):
    """Wraps a Java method so that data is converted on the way in and out.

    Inputs:
    - method - a bound Java method

    Outputs:
    - result - a callable taking Python data and returning Python data
    """

    def call(*args, **kwargs):
        args = [_to_java(a) for a in args]
        kwargs = {k: _to_java(v) for k, v in kwargs.items()}
        return _from_java(method(*args, **kwargs))

    call.__name__ = getattr(method, "__name__", "call")
    call.__doc__ = getattr(method, "__doc__", None)
    return call


class _Wrapper:
    """A Java class or object, with its data converted as it is used.

    Attribute access is passed straight through, so that a calculator is
    used exactly as it is in Java; each method is wrapped so that
    observations may be given as lists or numpy arrays, and results such as
    local values come back as numpy arrays.
    """

    __slots__ = ("_java",)

    def __init__(self, java):
        object.__setattr__(self, "_java", java)

    def __getattr__(self, name):
        attribute = getattr(self._java, name)
        if callable(attribute):
            return _call(attribute)
        return _from_java(attribute)

    def __setattr__(self, name, value):
        setattr(self._java, name, _to_java(value))

    def __call__(self, *args, **kwargs):
        # Constructing a calculator, or calling the class itself:
        return _call(self._java)(*args, **kwargs)

    def __repr__(self):
        return repr(self._java)

    def __str__(self):
        return str(self._java)
