/**
 * This package hosts Java code that is generated by the AutoAnalyser.
 * 
 * <p>We're not really planning to generate Javadocs for these classes,
 *    simply putting this file here so that the otherwise empty folder
 *    can be added to git (we need the folder here ready for 
 *    the generated code to be put into).</p>
 * 
 * @author Joseph Lizier (<a href="joseph.lizier at gmail.com">email</a>,
 * <a href="http://lizier.me/joseph/">www</a>)
 */
package infodynamics.demos.autoanalysis;
